#!/bin/bash
set -e
cd "$(dirname "$0")"

# Build CM6 bundle
npm install --prefix .
npx esbuild cm_entry.js --bundle --format=esm --outfile=vendor/codemirror.js

# Build WASM
wasm-pack build --target web ../wasm/ --out-dir ../site/pkg/

# Generate stdlib JS module from stdlib/**/*.ml files
echo "// Auto-generated by build.sh — do not edit" > stdlib_files.js
echo "export const STDLIB_FILES = {" >> stdlib_files.js
while IFS= read -r f; do
    # Convert path relative to stdlib/ into dot-separated module name (without .ml)
    rel="${f#../stdlib/}"
    name=$(echo "${rel%.ml}" | tr '/' '.')
    # JSON-encode the file content
    content=$(node -e "process.stdout.write(JSON.stringify(require('fs').readFileSync('$f','utf8')))")
    echo "    \"$name\": $content," >> stdlib_files.js
done < <(find ../stdlib -name '*.ml' | sort)
echo "};" >> stdlib_files.js
